//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuRM.Portrait.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillCancellation
    {
        public int Id { get; set; }
        public string Reason { get; set; }
    
        public virtual BillHead BillHead { get; set; }
    }
}
