//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuRM.Portrait.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestImage
    {
        public int Id { get; set; }
        public int RequestHeadId { get; set; }
        public byte[] Data { get; set; }
    
        public virtual RequestHead RequestHead { get; set; }
    }
}
